spring:
  application:
    name: PopCoinSystem
    version: 1.0.0

server:
  port: 9999

logging:
  level:
    root: INFO

system:
  # 网络版本 决定这个服务能否参与网络共识
  netVersion: 1
  # 公钥 持有公钥的人能够控制这个节点
  publicKey:
    - 1321313132
    - 1321313132
    - 3123131324

kademlia:
  nodeType: 1
  node:
    tcpPort: 8334
    udpPort: 8333
  #配置引导节点
  bootstrap:
    - ip: 192.168.137.102
      tcpPort: 8334
      udpPort: 8333
      nodeId: 0