spring:
  application:
    name: PopCoinSystem
    version: 1.0.0

server:
  port: 9999

logging:
  level:
    root: INFO

system:
  #存储路径 全路径
  storagePath: /ec/storage
  #挖矿方式
  start-mining: 0 # 0关闭挖矿 1开启挖矿
  mining-type: 2 # 1CPU 2GPU

  # 网络版本 决定这个服务能否参与网络共识
  netVersion: 1
  mining:
    #基础奖励地址
    miner-address: bc1qzlxafwx7ccj97pfexxtml0u8u5v4jm6d5alpgpu #未配置就会使用中本聪的地址
    #手续费地址
    fee-address: bc1qzlxafwx7ccj97pfexxtml0u8u5v4jm6d5alpgpu #未配置就会使用中本聪的
    merge-tx-out: 1
  # 公钥 只有私钥可以控制节点
  publicKey:
    - 1321313132
    - 1321313132

kademlia:
  nodeType: 1  #1全节点 #2轻节点 #仅出站
  node:
    tcpPort: 8333
    udpPort: 8334
  isBootstrap: 0 # 0不连接到引导节点  1连接
  bootstrap:
    - ip: 192.168.137.102
      tcp-port: 8333
      udp-port: 8334
      node-id: 0

